name: ci
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build-kernel:
    strategy:
        matrix:
           vm:
           - test
           channel:
           - nixos-unstable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:${{matrix.channel}}
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Build VM
      run: nix build '.#nixosConfigurations.${{matrix.vm}}.config.system.build.vm'
